CREATE SCHEMA productrepo AUTHORIZATION postgres;
-- productrepo.product definition

-- Drop table

-- DROP TABLE productrepo.product;

CREATE TABLE productrepo.product (
                                     id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                     price float8 NULL,
                                     title varchar(255) NULL
);