server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - Get
              - Post
            allowedHeaders: "*"
      routes:
        - id: product-service
          uri: "http://localhost:8180"
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1
            - PrefixPath=/app
            - JwtAuthFilter
        - id: front-service
          uri: "http://localhost:8181"
          predicates:
            - Path=/app/**
          filters:
            - StripPrefix=1
            - PrefixPath=/app-front/
            - JwtAuthFilter
        - id: basket-service
          uri: "http://localhost:3000"
          predicates:
            - Path=/basket-service/**
          filters:
            - StripPrefix=1
            - PrefixPath=/app-basket
            - JwtAuthFilter
        - id: order-service
          uri: "http://localhost:8180"
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
            - PrefixPath=/app
            - JwtAuthFilter
        - id: auth-service
          uri: "http://localhost:8183"
          predicates:
            - Path=/auth
          filters:
            - StripPrefix=1
            - PrefixPath=/app-auth/auth
#      default-filters:
#        - DedupeResponseHeader = Access-Control-Allow-Credentials Access-Control-Allow-Origin

#            - JwtAuthFilter

jwt:
  secretKey: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g
  lifeTimeToken: 36000000