-- DROP SCHEMA productrepo;

CREATE SCHEMA productrepo AUTHORIZATION postgres;

-- DROP SEQUENCE productrepo.buyer_id_seq;

CREATE SEQUENCE productrepo.buyer_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;
-- DROP SEQUENCE productrepo.cheque_id_seq;

CREATE SEQUENCE productrepo.cheque_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;
-- DROP SEQUENCE productrepo.chequeline_id_seq;

CREATE SEQUENCE productrepo.chequeline_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;
-- DROP SEQUENCE productrepo.product_id_seq;

CREATE SEQUENCE productrepo.product_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE;-- productrepo.buyer definition

-- Drop table

-- DROP TABLE productrepo.buyer;

CREATE TABLE productrepo.buyer (
                                   id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                   "name" varchar(255) NULL,
                                   CONSTRAINT buyer_pkey PRIMARY KEY (id)
);


-- productrepo.product definition

-- Drop table

-- DROP TABLE productrepo.product;

CREATE TABLE productrepo.product (
                                     id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                     price float8 NULL,
                                     title varchar(255) NULL,
                                     CONSTRAINT product_pkey PRIMARY KEY (id)
);


-- productrepo.cheque definition

-- Drop table

-- DROP TABLE productrepo.cheque;

CREATE TABLE productrepo.cheque (
                                    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    datatime timestamp NULL,
                                    buyer_id int8 NULL,
                                    CONSTRAINT cheque_pkey PRIMARY KEY (id),
                                    CONSTRAINT cheque_buyer_id FOREIGN KEY (buyer_id) REFERENCES productrepo.buyer(id)
);


-- productrepo.chequeline definition

-- Drop table

-- DROP TABLE productrepo.chequeline;

CREATE TABLE productrepo.chequeline (
                                        id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                        price float8 NOT NULL,
                                        quantity float8 NOT NULL,
                                        cheque_id int8 NULL,
                                        product_id int8 NULL,
                                        CONSTRAINT chequeline_pkey PRIMARY KEY (id),
                                        CONSTRAINT chequeline_product_id FOREIGN KEY (product_id) REFERENCES productrepo.product(id),
                                        CONSTRAINT chequeline_cheque_id FOREIGN KEY (cheque_id) REFERENCES productrepo.cheque(id)
);
